services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    environment:
      APP_ENV: "dev"
      APP_SECRET: "a9806d99cd5c1503d8af30c963c9411f"
      DATABASE_URL: "mysql://user:password@database:3306/symfony-bootstrap"
  database:
    image: 'mysql:8.2.0'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "symfony-bootstrap"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
