parameters:
  app.service_canonical_name: 'test-blog.dev'
services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $serviceCanonicalName: '%app.service_canonical_name%'
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Migrations/'
      - '../src/Kernel.php'
